# .goreleaser.yaml

version: 2

# ---------------------------
# General
# ---------------------------
before:
  hooks:
    - make all
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^.github:'
      - '^.vscode:'
      - '^test:'

# ---------------------------
# Builders
# ---------------------------
builds:
  - skip: true

# ---------------------------
# GitHub Release
# ---------------------------
release:
  prerelease: false
  name_template: "Release v{{ .Version }}"

# ---------------------------
# Announce
# ---------------------------
announce:
  slack:
    enabled: false
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Changelog: https://github.com/BitcoinSchema/{{ .ProjectName }}/releases/tag/{{ .Tag }}'
    channel: '#test_slack'
    # username: ''
    # icon_emoji: ''
    # icon_url: ''

  twitter:
    enabled: false
    message_template: '{{ .ProjectName }} {{ .Tag }} is out!'

  discord:
    enabled: false
    message_template: '{{ .ProjectName }} {{ .Tag }} is out!'
    # author: ''
    # color: ''
    # icon_url: ''

  reddit:
    enabled: false
    application_id: ""
    username: ""
    title_template: '{{ .ProjectName }} {{ .Tag }} is out!'
    # url_template: 'https://github.com/BitcoinSchema/{{ .ProjectName }}/releases/tag/{{ .Tag }}'